/**
 * layout.jsx
 */

import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "@/components/Providers";
import { Toaster } from "react-hot-toast";
import MainNav from "@/components/navigation/MainNav";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth-options";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tech News",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <div className="">
            <MainNav session={session} />
            <div>{children}</div>
          </div>

          <Toaster />
        </NextAuthProvider>
      </body>
    </html>
  );
}
