// /**
//  * comp.jsx
//  */

// "use client";

// import React from "react";
// import Spline from "@splinetool/react-spline";

// const Comp = () => {
//   return (

//     // <Spline scene="https://prod.spline.design/yPoDsXGlCPu0DcNG/scene.splinecode" />
//   );
// };

// export default Comp;
/*
  Auto-generated by Spline
*/

"use client";

// import useSpline from "@splinetool/r3f-spline";
import {
  OrthographicCamera,
  PerspectiveCamera,
  Sphere,
} from "@react-three/drei";
import { Canvas } from "@react-three/fiber";

export default function Comp({ ...props }) {
  // const { nodes, materials } = useSpline(
  //   "https://prod.spline.design/u0vHYWyNTKedZbt4/scene.splinecode"
  // );
  return (
    <>
      <Canvas>
        <PerspectiveCamera position={[0, 2, 10]} />
        <color attach="background" args={["#000000"]} />
        <group {...props} dispose={null}>
          <scene name="Scene 1">
            <mesh
              name="Sphere"
              // geometry={Sphere}
              // geometry={nodes.Sphere.geometry}
              // material={materials["Sphere Material"]}
              castShadow
              receiveShadow
              position={[0, 0, 0.48]}
              rotation={[2.8, -0.47, -Math.PI]}
              scale={1}
            />{" "}
            <sphereGeometry args={[1, 16, 16]} />
            <meshStandardMaterial color="hotpink" transparent />
            <directionalLight
              name="Directional Light"
              castShadow
              intensity={1.18}
              shadow-mapSize-width={4096}
              shadow-mapSize-height={4096}
              shadow-camera-near={-10000}
              shadow-camera-far={100000}
              shadow-camera-left={-3223.077}
              shadow-camera-right={3223.077}
              shadow-camera-top={3223.077}
              shadow-camera-bottom={-3223.077}
              position={[200, 300, 1109.19]}
            />
            <OrthographicCamera
              name="1"
              makeDefault={true}
              far={10000}
              near={-50000}
            />
            <hemisphereLight
              name="Default Ambient Light"
              intensity={-0.05}
              color="#eaeaea"
            />
          </scene>
        </group>
      </Canvas>
    </>
  );
}
